### PR TITLE
Revert "switched to a supported fork of the tail library"

### PR DESCRIPTION
**Pull request by leucos**
Reverts devops-works/dw-query-digest#6

### CODE REVIEW

**Comment by leucos** [comment]
Seems there is an issue regardingmodule checksum:
```ERRO[178037] exit status 1: go: finding github.com/nxadm/tail v1.4.1
verifying github.com/nxadm/tail@v1.4.1: checksum mismatch
        downloaded: h1:IvsH0xPk6Z+ORn/PoTiBbD2Ig7241sucVgFy4S/5nas=
        sum.golang.org: h1:Vw207joT1RO2/h2d+lr3BdpTt1LVvBX4sjdiK5Zitu4=
```
Reverting this until this is sorted out @glaslos

**Comment by leucos** [comment]
Upstream: https://github.com/nxadm/tail/issues/12

**Comment by nxadm** [comment]
Fixed with a fresh tag (https://github.com/nxadm/tail/tree/v1.4.4). Sorry for the inconvenience.

**Comment by leucos** [comment]
Thanks a lot and now worries. At least we checked that this new go sum thingy works properly ;)

**Pull request merged**
